# originally started with this but feels better to not work on the default environment
# install me with:
# conda env update --file environment.yml <- did work
# mamba env update --file environment.yml
# conda env update -n base --file environment.yml <- didn't work
# name: base

# to create
# conda env create --file environment.yml
# or to move quicker
# conda install mamba
# mamba env create --file environment.yml

# To determine how to update
# should be able to record me with either of the following
# https://github.com/conda/conda/issues/9399
# conda env export --no-builds
# conda env export --no-builds --from-history

# to use:
# conda activate sars-cov2-pangenome-analysis
name: sars-cov2-pangenome-analysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - ncbi-datasets-cli
  - snakemake
  - bandage
