#!/bin/bash

# curl https://rclone.org/install.sh | sudo bash

# non-sudo rclone install
wget https://downloads.rclone.org/rclone-current-linux-amd64.zip
unzip rclone-current-linux-amd64.zip
rm rclone-current-linux-amd64.zip
# cd rclone-*-linux-amd64
mkdir -p ~/.local/bin/
cp rclone-*-linux-amd64/rclone ~/.local/bin/
chmod +x ~/.local/bin/rclone
mkdir -p ~/.local/share/man/man1
cp rclone-*-linux-amd64/rclone.1 ~/.local/share/man/man1
rm -r rclone-*-linux-amd64

# copy dotfiles to home directory
[[ ! -f "$HOME/workspace/dotfiles/copy-to-home.sh" ]] && bash $HOME/workspace/dotfiles/copy-to-home.sh

# julia -e 'import Pkg; Pkg.add(url="https://github.com/cjprybol/Mycelia.git", rev="master")'
julia \
    --project="$HOME/workspace/sars-cov2-pangenome-analysis" \
    --startup-file=no \
    'import Pkg; Pkg.instantiate()'